export const MESSAGES_LOAD_START = "MESSAGES_LOAD_START";
export const MESSAGES_LOAD_SUCCESS = "MESSAGES_LOAD_SUCCESS";
export const MESSAGES_LOAD_FAIL = "MESSAGES_LOAD_FAIL";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const AUTH_CHECK_START = 'AUTH_CHECK_START';
export const AUTH_CHECK_SUCCESS = 'AUTH_CHECK_SUCCESS'
export const AUTH_CHECK_FAIL = 'AUTH_CHECK_FAIL'
